### ISSUE TITLE
Module links to v4

### ISSUE THREAD

**Issue by cgolds2** [MadManNBlueBox/wands#12] opened 2021-11-18 06:09 UTC
I think these might be the lines causing the issue
https://github.com/MadManNBlueBox/wands/blob/431d92d0fb6ddd8f43dc71e2c776286be8ce8b08/module.json#L147-L148

But when downloading
https://github.com/MadManNBlueBox/wands/releases/download/0.5.0/module.json 
to foundry, v4 is installed instead

**Comment by MadManNBlueBox** [comment] 2021-11-18 15:14
It has been fixed. Thank you for pointing that out.

Please let me know if you have any feedback on the module. Anything you wish it had or if you think something could be done a better way. Also if you notice any mistakes or typo I am one person things are sure to be over looked.

Thanks again for the catch. Hope you enjoy the module and have a magical game!

**Comment by cgolds2** [comment] 2021-11-19 05:26
I just updated and it pulled the new version, but then I get

`{"level":"error","timestamp":"2021-11-19 05:23:49","message":"The wands.animagus-form-wands Datastore is not yet connected!","stack":"Error: The wands.animagus-form-wands Datastore is not yet connected!\n    at Function.get db [as db] (file:///home/foundry/resources/app/dist/database/backend/server-document.mjs:1:625)\n    at ServerDatabaseBackend._getDocuments (file:///home/foundry/resources/app/dist/database/backend/server-backend.mjs:1:1032)\n    at Function.getIndex (file:///home/foundry/resources/app/dist/database/backend/server-compendium.mjs:1:1139)\n    at Function.vend (file:///home/foundry/resources/app/dist/packages/world.mjs:1:9179)\n    at async Function.requestWorldData (file:///home/foundry/resources/app/dist/packages/world.mjs:1:7519)"}
`

and if i delete it out that in the module json, I get

`{"level":"error","timestamp":"2021-11-19 05:24:03","message":"The wands.wands-roll-tables Datastore is not yet connected!","stack":"Error: The wands.wands-roll-tables Datastore is not yet connected!\n    at Function.get db [as db] (file:///home/foundry/resources/app/dist/database/backend/server-document.mjs:1:625)\n    at ServerDatabaseBackend._getDocuments (file:///home/foundry/resources/app/dist/database/backend/server-backend.mjs:1:1032)\n    at Function.getIndex (file:///home/foundry/resources/app/dist/database/backend/server-compendium.mjs:1:1139)\n    at Function.vend (file:///home/foundry/resources/app/dist/packages/world.mjs:1:9179)\n    at async Function.requestWorldData (file:///home/foundry/resources/app/dist/packages/world.mjs:1:7519)"}`

If I delete that in the json, it loads (thought the animagus and wands are left out)

Do you know if this is something that I am doing wrong?

**Comment by MadManNBlueBox** [comment] 2021-11-19 05:36
I think I may not what the issue is but won't be able to look at it till tomorrow morning.

If you go into the module folder for WANDS, there should be a folder labeled "packs." In that folder do you see Data Base Files called "animagus-form-wands" and "wands-roll-tables"?

**Comment by cgolds2** [comment] 2021-11-19 05:37
Im actually able to see the db files as well as see that they contain text, so Im not sure why its having trouble consuming it

**Comment by MadManNBlueBox** [comment] 2021-11-19 05:41
What version of Foundry are you running?

What version of DnD5e are you running?

**Comment by MadManNBlueBox** [comment] 2021-11-19 05:42
Are there any other modules you are running along side with it?

**Comment by cgolds2** [comment] 2021-11-19 05:42
Foundry 0.8.9
DnD 1.5.5

**Comment by cgolds2** [comment] 2021-11-19 05:43
- Dice so Nice
- Moulinette
- Pings
- Settings Extender
- Simple Dice roller

**Comment by MadManNBlueBox** [comment] 2021-11-19 05:45
Would you mind try running it without any other module and see if you still get the error?

**Comment by MadManNBlueBox** [comment] 2021-11-19 05:51
Another thing that might be worth trying is uninstalling the module and reinstalling it. It's possible with the original error, having the wrong version in the .json file, may have confused the update.

**Comment by MadManNBlueBox** [comment] 2021-11-19 05:53
Let me know if any of that works. If not, I will look more into it into the morning. A 0.5.1 version is on its way with the few changes that Murphen made to the rulebook. Maybe the update to a new version number will help.

**Comment by cgolds2** [comment] 2021-11-19 05:56
Tried both
Deleted and reinstalled
Made brand new world, just added this module, same errors

**Comment by MadManNBlueBox** [comment] 2021-11-19 05:58
Thank you trying all those things. I will look into it in the morning.

**Comment by MadManNBlueBox** [comment] 2021-11-19 20:02
So I got called into work this morning. I'll try to work on this tomorrow. Apologies if this is causing any inconvenience.

**Comment by MadManNBlueBox** [comment] 2021-11-22 15:06
So I have had other run the module and have not been able to recreate the error you are having. I am not sure what is causing it or why it is happening to you. I am going to close this for not sense it doesn't seem to be on the module end of it. I will be releasing v 0.5.1 soon. Maybe that will fix it.

**Comment by cgolds2** [comment] 2021-11-23 06:27
So I  was testing this, and found that even when I made a custom module, I got the same error
Weirdly, none of the other modules I've installed have ran into this
However, while looking through the FVTT Discord, I saw someone else had the issue and I think its because of running inside a docker container. The way they fixed it is by adding the system and module params to the module.json items
eg

```
    },
    {
      "name": "animagus-form-wands",
      "label": "Animagus Form (WANDS)",
      "system": "dnd5e",
      "path": "./packs/animagus-form-wands.db",
      "entity": "Actor",
      "private": false,
            "system": "dnd5e",
            "module": "wands"
    },
    {
      "name": "wands-roll-tables",
      "label": "WANDS Roll Tables (WANDS)",
      "system": "dnd5e",
      "path": "./packs/wands-roll-tables.db",
      "entity": "RollTable",
      "private": false,
            "system": "dnd5e",
            "module": "wands"
    }
 ```


I have no idea why this works, but it seems like it solves the problem

**Comment by MadManNBlueBox** [comment] 2021-11-23 16:32
How strange. Why would this only happen with these 2 packs? Also writing it that way, `"system": "dnd5e"` is now in there twice and a 3rd time after packs.

Also, adding `"module": "wands"` seems redundant.

This is very strange that it would fix your issue. I am going to look into some other updated module and see if they have changed any of the code for compendiums.

Glad you were able to make it work for you. Once I look into some other modules I will decided what to do to changing mine. For now I am going to leave it as it is.

**Comment by MadManNBlueBox** [comment] 2021-11-23 16:57
So looking of other modules `"module": "(module name)"` seems to be added recently. Maybe it has something to do with 0.8.9.

If you just add `"module": "wands"` does it still fix the issue?

**Comment by cgolds2** [comment] 2021-11-29 07:15
Sorry for the late reply, got caught up in holiday things
It looks like just module fixes it
So strange haha

```
    {
      "name": "animagus-form-wands",
      "label": "Animagus Form (WANDS)",
      "system": "dnd5e",
      "path": "./packs/animagus-form-wands.db",
      "entity": "Actor",
      "private": false,
            "module": "wands"
    },
    {
      "name": "wands-roll-tables",
      "label": "WANDS Roll Tables (WANDS)",
      "system": "dnd5e",
      "path": "./packs/wands-roll-tables.db",
      "entity": "RollTable",
      "private": false,
            "module": "wands"
    }
```

**Comment by MadManNBlueBox** [comment] 2021-12-29 01:07
Made these changes in 0.5.2. Thank you for your help resolving that issue. Happy Holidays!

**Closed as completed by MadManNBlueBox** 2021-12-29 01:07 UTC
